# action.yml
name: 'Push to Codepost.io'
description: 'Copy a student submission to codepost.io and auto trigger tests'
inputs:
  codepost-api-token:
    description: 'API Token for Codepost.io'
    required: true
    default: ''
  assignment-id:
    description: 'The id of the Codepost.io assignment you are pushing to'
    required: true
    default: ''
  github-user:
    description: 'The github username of the person pushing'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://bjucps/codepost-bju-push:v1.0.8'
  args:
    - ${{ inputs.codepost-api-token }}
    - ${{ inputs.assignment-id }}
    - ${{ inputs.github-user }}